// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'shared/models/troodking_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 615830367803679989),
    name: 'CategorieItem',
    lastPropertyId: const obx_int.IdUid(6, 4912197750162704758),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1876116820623470780),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2542808865166489382),
        name: 'nameItem',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8001109355283604972),
        name: 'priceItem',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7454812313517193435),
        name: 'grams',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3313276793848296581),
        name: 'macrosId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 5112664903495154962),
        relationField: 'macros',
        relationTarget: 'Macros',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4912197750162704758),
        name: 'troodkingModelId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 8505377993418805567),
        relationField: 'troodkingModel',
        relationTarget: 'TroodkingModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2533252362119871382),
    name: 'Macros',
    lastPropertyId: const obx_int.IdUid(3, 3239251155639147993),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6551850602464281857),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6131834973885866272),
        name: 'calories',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3239251155639147993),
        name: 'protein',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5014434234308960145),
    name: 'TroodkingModel',
    lastPropertyId: const obx_int.IdUid(3, 402482469894003145),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8416022373056310673),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1679099095291572667),
        name: 'categorieName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 402482469894003145),
        name: 'categorieIcon',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 4389249027511755564),
        name: 'categorieItems',
        targetId: const obx_int.IdUid(1, 615830367803679989),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 5014434234308960145),
    lastIndexId: const obx_int.IdUid(2, 8505377993418805567),
    lastRelationId: const obx_int.IdUid(1, 4389249027511755564),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CategorieItem: obx_int.EntityDefinition<CategorieItem>(
      model: _entities[0],
      toOneRelations: (CategorieItem object) => [
        object.macros,
        object.troodkingModel,
      ],
      toManyRelations: (CategorieItem object) => {},
      getId: (CategorieItem object) => object.id,
      setId: (CategorieItem object, int id) {
        object.id = id;
      },
      objectToFB: (CategorieItem object, fb.Builder fbb) {
        final nameItemOffset = object.nameItem == null
            ? null
            : fbb.writeString(object.nameItem!);
        final gramsOffset = object.grams == null
            ? null
            : fbb.writeString(object.grams!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameItemOffset);
        fbb.addFloat64(2, object.priceItem);
        fbb.addOffset(3, gramsOffset);
        fbb.addInt64(4, object.macros.targetId);
        fbb.addInt64(5, object.troodkingModel.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameItemParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final priceItemParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final gramsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = CategorieItem(
          id: idParam,
          nameItem: nameItemParam,
          priceItem: priceItemParam,
          grams: gramsParam,
        );
        object.macros.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.macros.attach(store);
        object.troodkingModel.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.troodkingModel.attach(store);
        return object;
      },
    ),
    Macros: obx_int.EntityDefinition<Macros>(
      model: _entities[1],
      toOneRelations: (Macros object) => [],
      toManyRelations: (Macros object) => {},
      getId: (Macros object) => object.id,
      setId: (Macros object, int id) {
        object.id = id;
      },
      objectToFB: (Macros object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.calories);
        fbb.addFloat64(2, object.protein);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final caloriesParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final proteinParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final object = Macros(
          id: idParam,
          calories: caloriesParam,
          protein: proteinParam,
        );

        return object;
      },
    ),
    TroodkingModel: obx_int.EntityDefinition<TroodkingModel>(
      model: _entities[2],
      toOneRelations: (TroodkingModel object) => [],
      toManyRelations: (TroodkingModel object) => {
        obx_int.RelInfo<TroodkingModel>.toMany(1, object.id):
            object.categorieItems,
      },
      getId: (TroodkingModel object) => object.id,
      setId: (TroodkingModel object, int id) {
        object.id = id;
      },
      objectToFB: (TroodkingModel object, fb.Builder fbb) {
        final categorieNameOffset = object.categorieName == null
            ? null
            : fbb.writeString(object.categorieName!);
        final categorieIconOffset = object.categorieIcon == null
            ? null
            : fbb.writeString(object.categorieIcon!);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, categorieNameOffset);
        fbb.addOffset(2, categorieIconOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final categorieNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final categorieIconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = TroodkingModel(
          id: idParam,
          categorieName: categorieNameParam,
          categorieIcon: categorieIconParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<TroodkingModel>(
          object.categorieItems,
          store,
          obx_int.RelInfo<TroodkingModel>.toMany(1, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CategorieItem] entity fields to define ObjectBox queries.
class CategorieItem_ {
  /// See [CategorieItem.id].
  static final id = obx.QueryIntegerProperty<CategorieItem>(
    _entities[0].properties[0],
  );

  /// See [CategorieItem.nameItem].
  static final nameItem = obx.QueryStringProperty<CategorieItem>(
    _entities[0].properties[1],
  );

  /// See [CategorieItem.priceItem].
  static final priceItem = obx.QueryDoubleProperty<CategorieItem>(
    _entities[0].properties[2],
  );

  /// See [CategorieItem.grams].
  static final grams = obx.QueryStringProperty<CategorieItem>(
    _entities[0].properties[3],
  );

  /// See [CategorieItem.macros].
  static final macros = obx.QueryRelationToOne<CategorieItem, Macros>(
    _entities[0].properties[4],
  );

  /// See [CategorieItem.troodkingModel].
  static final troodkingModel =
      obx.QueryRelationToOne<CategorieItem, TroodkingModel>(
        _entities[0].properties[5],
      );
}

/// [Macros] entity fields to define ObjectBox queries.
class Macros_ {
  /// See [Macros.id].
  static final id = obx.QueryIntegerProperty<Macros>(
    _entities[1].properties[0],
  );

  /// See [Macros.calories].
  static final calories = obx.QueryDoubleProperty<Macros>(
    _entities[1].properties[1],
  );

  /// See [Macros.protein].
  static final protein = obx.QueryDoubleProperty<Macros>(
    _entities[1].properties[2],
  );
}

/// [TroodkingModel] entity fields to define ObjectBox queries.
class TroodkingModel_ {
  /// See [TroodkingModel.id].
  static final id = obx.QueryIntegerProperty<TroodkingModel>(
    _entities[2].properties[0],
  );

  /// See [TroodkingModel.categorieName].
  static final categorieName = obx.QueryStringProperty<TroodkingModel>(
    _entities[2].properties[1],
  );

  /// See [TroodkingModel.categorieIcon].
  static final categorieIcon = obx.QueryStringProperty<TroodkingModel>(
    _entities[2].properties[2],
  );

  /// see [TroodkingModel.categorieItems]
  static final categorieItems =
      obx.QueryRelationToMany<TroodkingModel, CategorieItem>(
        _entities[2].relations[0],
      );
}
